### ISSUE TITLE
Answers of the model are garbled code

### ISSUE THREAD

**Issue by imzhaoruijie** [haotian-liu/LLaVA#48] opened 2023-04-24 03:20 UTC
When I Launched a gradio web server, I could open my browser and chat with a model. However, the answers of the model are garbled code.
How can I fix this problem? There is no error information.

**Comment by haotian-liu** [comment] 2023-04-24 03:25
Hi, thank you for your interest in our work.  To troubleshoot the issue, please check and confirm the following,

1. Please create converted LLaVA weight from LLaMA checkpoint following the instructions [here](https://github.com/haotian-liu/LLaVA#llava-13b).  Note: our delta weights are relative to **LLaMA** instead of Vicuna.
2. The converted model should contain "LLaVA" at least once to load the correct prompts (#46).
3. If the above two does not solve your problem, please share the command, and the log from the worker and gradio (specifically, it will print out a log that includes the prompt and the response, please screenshot or paste that here with ``` code block), as well as the output so that we can better troubleshoot.

Thanks.

**Comment by imzhaoruijie** [comment] 2023-04-24 06:42
Thanks for your response!
I checked the steps but did not solve the garbled code.
And here is the specific information:

1.When running, the model name contains LLaVA.
python3 -m llava.model.apply_delta --base llama-13b/ --target output_LLaVA-13B-v0/ --delta LLaVA-13b-delta-v0/

2.
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/49706142/233916944-744dd8f7-b33e-479e-9d23-c55cea3549a6.png">

3.
root@ctmt2304211537279nb-6cc856d9db-hslcd:/mnt/home/LLaVA-main# python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path output_LLaVA-13B-v0  --multi-modal
2023-04-24 14:39:40 | INFO | model_worker | args: Namespace(controller_address='http://localhost:10000', host='0.0.0.0', keep_aspect_ratio=False, limit_model_concurrency=5, model_name=None, model_path='output_LLaVA-13B-v0', multi_modal=True, no_register=False, num_gpus=1, port=40000, stream_interval=2, worker_address='http://localhost:40000')
2023-04-24 14:39:40 | INFO | model_worker | Loading the model output_LLaVA-13B-v0 on worker 8ca868 ...
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
2023-04-24 14:39:51 | INFO | stdout | path_or_repo_id openai/clip-vit-large-patch14
2023-04-24 14:39:51 | INFO | stdout | filename config.json
2023-04-24 14:39:51 | INFO | stdout | subfolder
2023-04-24 14:39:51 | INFO | stdout | cache_dir /root/.cache/huggingface/hub
2023-04-24 14:39:51 | INFO | stdout | local_files_only False
2023-04-24 14:39:51 | INFO | stdout | storage_folder /root/.cache/huggingface/hub/models--openai--clip-vit-large-patch14
2023-04-24 14:39:51 | INFO | stdout | local_dir None
2023-04-24 14:39:51 | INFO | stdout | url_to_download https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/config.json
2023-04-24 14:39:51 | INFO | stdout | filename config.json
2023-04-24 14:39:51 | INFO | stdout | revision main
2023-04-24 14:39:51 | INFO | stdout | cached_file /root/.cache/huggingface/hub/models--openai--clip-vit-large-patch14/clip-vit-large-patch14/config.json
2023-04-24 14:39:51 | INFO | stdout | !!!!!!!!!!!!!!!!!!!!
2023-04-24 14:39:51 | INFO | stdout | resolved_file /root/.cache/huggingface/hub/models--openai--clip-vit-large-patch14/clip-vit-large-patch14/config.json
2023-04-24 14:39:51 | INFO | stdout | path_or_repo_id openai/clip-vit-large-patch14
2023-04-24 14:39:51 | INFO | stdout | filename pytorch_model.bin
2023-04-24 14:39:51 | INFO | stdout | subfolder
2023-04-24 14:39:51 | INFO | stdout | cache_dir /root/.cache/huggingface/hub
2023-04-24 14:39:51 | INFO | stdout | local_files_only False
2023-04-24 14:39:51 | INFO | stdout | storage_folder /root/.cache/huggingface/hub/models--openai--clip-vit-large-patch14
2023-04-24 14:39:51 | INFO | stdout | local_dir None
2023-04-24 14:39:51 | INFO | stdout | url_to_download https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/pytorch_model.bin
2023-04-24 14:39:51 | INFO | stdout | filename pytorch_model.bin
2023-04-24 14:39:51 | INFO | stdout | revision main
2023-04-24 14:39:51 | INFO | stdout | cached_file /root/.cache/huggingface/hub/models--openai--clip-vit-large-patch14/clip-vit-large-patch14/pytorch_model.bin
2023-04-24 14:39:51 | INFO | stdout | !!!!!!!!!!!!!!!!!!!!
2023-04-24 14:39:51 | INFO | stdout | resolved_file /root/.cache/huggingface/hub/models--openai--clip-vit-large-patch14/clip-vit-large-patch14/pytorch_model.bin
Some weights of the model checkpoint at openai/clip-vit-large-patch14 were not used when initializing CLIPVisionModel: ['text_model.encoder.layers.2.mlp.fc1.weight', 'text_model.encoder.layers.7.mlp.fc1.weight', 'text_model.encoder.layers.11.self_attn.v_proj.weight', 'text_model.encoder.layers.4.mlp.fc1.weight', 'text_model.encoder.layers.8.self_attn.q_proj.weight', 'text_model.encoder.layers.4.self_attn.q_proj.bias', 'text_model.encoder.layers.6.self_attn.out_proj.bias', 'text_model.encoder.layers.8.self_attn.out_proj.bias', 'text_model.encoder.layers.6.self_attn.out_proj.weight', 'text_model.encoder.layers.8.self_attn.out_proj.weight', 'text_model.encoder.layers.0.self_attn.out_proj.bias', 'text_model.encoder.layers.5.self_attn.out_proj.bias', 'text_model.encoder.layers.7.self_attn.out_proj.weight', 'text_model.encoder.layers.10.mlp.fc1.bias', 'text_model.encoder.layers.5.mlp.fc1.bias', 'text_model.encoder.layers.4.mlp.fc1.bias', 'text_model.encoder.layers.7.mlp.fc2.bias', 'text_model.encoder.layers.4.self_attn.out_proj.weight', 'text_model.encoder.layers.9.mlp.fc2.weight', 'text_model.encoder.layers.2.mlp.fc2.weight', 'text_model.encoder.layers.7.self_attn.v_proj.bias', 'text_model.encoder.layers.0.mlp.fc2.weight', 'text_model.encoder.layers.2.self_attn.k_proj.bias', 'text_model.encoder.layers.0.self_attn.q_proj.bias', 'text_model.encoder.layers.3.self_attn.v_proj.bias', 'text_model.encoder.layers.6.mlp.fc2.bias', 'text_model.embeddings.token_embedding.weight', 'text_model.encoder.layers.9.self_attn.out_proj.bias', 'text_model.encoder.layers.9.mlp.fc1.bias', 'text_model.encoder.layers.2.mlp.fc2.bias', 'text_model.encoder.layers.3.self_attn.k_proj.bias', 'text_model.encoder.layers.7.self_attn.out_proj.bias', 'text_model.encoder.layers.11.mlp.fc1.bias', 'text_model.encoder.layers.6.self_attn.q_proj.bias', 'text_model.encoder.layers.4.self_attn.v_proj.bias', 'text_model.encoder.layers.11.mlp.fc1.weight', 'text_model.encoder.layers.3.self_attn.k_proj.weight', 'text_model.encoder.layers.0.layer_norm1.bias', 'text_model.encoder.layers.0.self_attn.v_proj.bias', 'text_model.encoder.layers.4.self_attn.q_proj.weight', 'text_model.encoder.layers.8.mlp.fc1.bias', 'text_model.encoder.layers.7.self_attn.q_proj.weight', 'text_model.encoder.layers.9.mlp.fc1.weight', 'text_model.encoder.layers.6.self_attn.k_proj.bias', 'text_model.encoder.layers.0.layer_norm1.weight', 'text_model.encoder.layers.2.self_attn.k_proj.weight', 'text_model.encoder.layers.10.self_attn.q_proj.bias', 'text_model.encoder.layers.2.self_attn.q_proj.bias', 'text_model.encoder.layers.7.self_attn.q_proj.bias', 'text_model.encoder.layers.2.self_attn.v_proj.bias', 'text_model.encoder.layers.1.self_attn.k_proj.weight', 'text_model.encoder.layers.7.layer_norm1.weight', 'text_model.encoder.layers.0.mlp.fc2.bias', 'text_model.encoder.layers.7.self_attn.k_proj.bias', 'text_model.encoder.layers.3.self_attn.v_proj.weight', 'text_model.encoder.layers.0.layer_norm2.bias', 'visual_projection.weight', 'text_model.encoder.layers.0.self_attn.v_proj.weight', 'text_model.encoder.layers.1.mlp.fc2.weight', 'text_model.encoder.layers.1.self_attn.v_proj.bias', 'text_model.encoder.layers.1.layer_norm1.bias', 'text_model.encoder.layers.6.self_attn.q_proj.weight', 'text_model.encoder.layers.5.self_attn.k_proj.weight', 'text_model.encoder.layers.6.self_attn.k_proj.weight', 'text_model.encoder.layers.9.self_attn.out_proj.weight', 'text_model.encoder.layers.4.self_attn.k_proj.bias', 'text_model.encoder.layers.2.self_attn.q_proj.weight', 'text_projection.weight', 'text_model.encoder.layers.8.mlp.fc2.bias', 'text_model.encoder.layers.11.layer_norm1.weight', 'text_model.encoder.layers.4.self_attn.out_proj.bias', 'text_model.encoder.layers.7.self_attn.v_proj.weight', 'text_model.encoder.layers.5.self_attn.k_proj.bias', 'text_model.encoder.layers.11.self_attn.k_proj.weight', 'text_model.encoder.layers.3.self_attn.q_proj.weight', 'text_model.encoder.layers.2.layer_norm1.bias', 'text_model.encoder.layers.11.self_attn.v_proj.bias', 'text_model.encoder.layers.10.layer_norm1.bias', 'text_model.encoder.layers.2.mlp.fc1.bias', 'text_model.encoder.layers.10.mlp.fc2.weight', 'text_model.encoder.layers.8.self_attn.v_proj.weight', 'text_model.encoder.layers.3.layer_norm1.weight', 'text_model.encoder.layers.9.self_attn.k_proj.weight', 'text_model.encoder.layers.0.self_attn.q_proj.weight', 'text_model.encoder.layers.8.self_attn.k_proj.bias', 'text_model.encoder.layers.5.self_attn.v_proj.weight', 'text_model.encoder.layers.7.self_attn.k_proj.weight', 'text_model.encoder.layers.8.layer_norm2.weight', 'text_model.encoder.layers.3.layer_norm1.bias', 'text_model.encoder.layers.4.layer_norm1.weight', 'text_model.encoder.layers.5.self_attn.q_proj.bias', 'text_model.encoder.layers.5.layer_norm2.weight', 'text_model.encoder.layers.4.mlp.fc2.weight', 'text_model.encoder.layers.0.layer_norm2.weight', 'text_model.encoder.layers.10.self_attn.k_proj.bias', 'text_model.encoder.layers.6.mlp.fc2.weight', 'text_model.encoder.layers.5.self_attn.q_proj.weight', 'text_model.encoder.layers.0.mlp.fc1.weight', 'text_model.encoder.layers.3.mlp.fc1.bias', 'text_model.encoder.layers.1.mlp.fc1.bias', 'text_model.encoder.layers.6.layer_norm1.bias', 'text_model.encoder.layers.9.self_attn.v_proj.weight', 'text_model.final_layer_norm.bias', 'text_model.encoder.layers.4.self_attn.k_proj.weight', 'text_model.encoder.layers.4.layer_norm2.weight', 'text_model.encoder.layers.9.self_attn.v_proj.bias', 'text_model.encoder.layers.4.layer_norm2.bias', 'text_model.encoder.layers.11.self_attn.out_proj.bias', 'text_model.encoder.layers.11.layer_norm2.weight', 'text_model.encoder.layers.5.self_attn.v_proj.bias', 'text_model.encoder.layers.10.layer_norm1.weight', 'text_model.encoder.layers.1.mlp.fc1.weight', 'text_model.encoder.layers.0.mlp.fc1.bias', 'text_model.encoder.layers.9.layer_norm2.bias', 'text_model.encoder.layers.3.mlp.fc2.bias', 'text_model.encoder.layers.10.self_attn.out_proj.bias', 'text_model.encoder.layers.1.layer_norm1.weight', 'text_model.encoder.layers.10.self_attn.k_proj.weight', 'text_model.encoder.layers.9.self_attn.k_proj.bias', 'text_model.encoder.layers.4.mlp.fc2.bias', 'text_model.encoder.layers.9.layer_norm2.weight', 'text_model.encoder.layers.9.mlp.fc2.bias', 'text_model.encoder.layers.3.self_attn.out_proj.bias', 'text_model.encoder.layers.6.layer_norm2.bias', 'text_model.encoder.layers.1.self_attn.out_proj.bias', 'text_model.embeddings.position_ids', 'text_model.encoder.layers.1.self_attn.out_proj.weight', 'text_model.encoder.layers.3.layer_norm2.bias', 'text_model.encoder.layers.6.layer_norm2.weight', 'text_model.encoder.layers.9.self_attn.q_proj.bias', 'text_model.encoder.layers.1.layer_norm2.weight', 'text_model.encoder.layers.0.self_attn.k_proj.weight', 'text_model.encoder.layers.10.mlp.fc2.bias', 'text_model.embeddings.position_embedding.weight', 'text_model.encoder.layers.10.self_attn.v_proj.weight', 'text_model.encoder.layers.3.layer_norm2.weight', 'text_model.encoder.layers.6.mlp.fc1.weight', 'text_model.encoder.layers.11.layer_norm2.bias', 'text_model.encoder.layers.11.mlp.fc2.weight', 'text_model.encoder.layers.7.mlp.fc1.bias', 'text_model.encoder.layers.8.self_attn.q_proj.bias', 'text_model.encoder.layers.10.layer_norm2.bias', 'text_model.encoder.layers.6.self_attn.v_proj.weight', 'text_model.encoder.layers.7.layer_norm2.bias', 'text_model.encoder.layers.2.self_attn.v_proj.weight', 'text_model.encoder.layers.8.layer_norm1.bias', 'text_model.encoder.layers.8.mlp.fc2.weight', 'text_model.encoder.layers.5.layer_norm2.bias', 'text_model.encoder.layers.7.layer_norm1.bias', 'text_model.encoder.layers.10.self_attn.out_proj.weight', 'text_model.encoder.layers.6.mlp.fc1.bias', 'text_model.encoder.layers.9.layer_norm1.weight', 'text_model.encoder.layers.0.self_attn.k_proj.bias', 'text_model.encoder.layers.1.layer_norm2.bias', 'text_model.encoder.layers.7.mlp.fc2.weight', 'text_model.encoder.layers.11.layer_norm1.bias', 'text_model.encoder.layers.9.layer_norm1.bias', 'text_model.encoder.layers.2.layer_norm1.weight', 'text_model.encoder.layers.2.layer_norm2.weight', 'text_model.encoder.layers.8.self_attn.v_proj.bias', 'text_model.encoder.layers.3.mlp.fc1.weight', 'text_model.encoder.layers.5.layer_norm1.weight', 'text_model.encoder.layers.5.self_attn.out_proj.weight', 'text_model.encoder.layers.8.layer_norm2.bias', 'text_model.encoder.layers.6.layer_norm1.weight', 'text_model.encoder.layers.10.self_attn.v_proj.bias', 'text_model.encoder.layers.11.self_attn.q_proj.bias', 'text_model.encoder.layers.2.layer_norm2.bias', 'text_model.encoder.layers.5.mlp.fc1.weight', 'text_model.encoder.layers.11.self_attn.out_proj.weight', 'text_model.encoder.layers.1.self_attn.v_proj.weight', 'text_model.encoder.layers.11.mlp.fc2.bias', 'text_model.encoder.layers.1.self_attn.k_proj.bias', 'text_model.encoder.layers.1.self_attn.q_proj.weight', 'text_model.encoder.layers.8.self_attn.k_proj.weight', 'text_model.encoder.layers.11.self_attn.q_proj.weight', 'text_model.encoder.layers.3.self_attn.out_proj.weight', 'text_model.encoder.layers.6.self_attn.v_proj.bias', 'text_model.encoder.layers.5.mlp.fc2.weight', 'text_model.encoder.layers.1.mlp.fc2.bias', 'text_model.encoder.layers.3.self_attn.q_proj.bias', 'text_model.encoder.layers.2.self_attn.out_proj.weight', 'text_model.encoder.layers.3.mlp.fc2.weight', 'text_model.encoder.layers.5.mlp.fc2.bias', 'text_model.encoder.layers.10.mlp.fc1.weight', 'text_model.encoder.layers.9.self_attn.q_proj.weight', 'text_model.encoder.layers.8.layer_norm1.weight', 'text_model.encoder.layers.0.self_attn.out_proj.weight', 'text_model.encoder.layers.2.self_attn.out_proj.bias', 'text_model.encoder.layers.11.self_attn.k_proj.bias', 'text_model.final_layer_norm.weight', 'text_model.encoder.layers.5.layer_norm1.bias', 'logit_scale', 'text_model.encoder.layers.8.mlp.fc1.weight', 'text_model.encoder.layers.10.self_attn.q_proj.weight', 'text_model.encoder.layers.7.layer_norm2.weight', 'text_model.encoder.layers.10.layer_norm2.weight', 'text_model.encoder.layers.1.self_attn.q_proj.bias', 'text_model.encoder.layers.4.layer_norm1.bias', 'text_model.encoder.layers.4.self_attn.v_proj.weight']
- This IS expected if you are initializing CLIPVisionModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing CLIPVisionModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Loading checkpoint shards:   0%|                                                                                                   | 0/3 [00:00<?, ?it/s]
Loading checkpoint shards:  33%|██████████████████████████████▎                                                            | 1/3 [00:03<00:06,  3.44s/it]
Loading checkpoint shards:  67%|████████████████████████████████████████████████████████████▋                              | 2/3 [00:07<00:03,  3.57s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:11<00:00,  3.61s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:11<00:00,  3.67s/it]
2023-04-24 14:40:04 | ERROR | stderr | 
2023-04-24 14:40:06 | INFO | stdout | path_or_repo_id openai/clip-vit-large-patch14
2023-04-24 14:40:06 | INFO | stdout | filename preprocessor_config.json
2023-04-24 14:40:06 | INFO | stdout | subfolder
2023-04-24 14:40:06 | INFO | stdout | cache_dir /root/.cache/huggingface/hub
2023-04-24 14:40:06 | INFO | stdout | local_files_only False
2023-04-24 14:40:06 | INFO | stdout | storage_folder /root/.cache/huggingface/hub/models--openai--clip-vit-large-patch14
2023-04-24 14:40:06 | INFO | stdout | local_dir None
2023-04-24 14:40:06 | INFO | stdout | url_to_download https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/preprocessor_config.json
2023-04-24 14:40:06 | INFO | stdout | filename preprocessor_config.json
2023-04-24 14:40:06 | INFO | stdout | revision main
2023-04-24 14:40:06 | INFO | stdout | cached_file /root/.cache/huggingface/hub/models--openai--clip-vit-large-patch14/clip-vit-large-patch14/preprocessor_config.json
2023-04-24 14:40:06 | INFO | stdout | !!!!!!!!!!!!!!!!!!!!
2023-04-24 14:40:06 | INFO | stdout | resolved_file /root/.cache/huggingface/hub/models--openai--clip-vit-large-patch14/clip-vit-large-patch14/preprocessor_config.json
2023-04-24 14:40:14 | INFO | model_worker | Register to controller
2023-04-24 14:40:14 | ERROR | stderr | INFO:     Started server process [58522]
2023-04-24 14:40:14 | INFO | uvicorn.error | Started server process [58522]
2023-04-24 14:40:14 | ERROR | stderr | INFO:     Waiting for application startup.
2023-04-24 14:40:14 | INFO | uvicorn.error | Waiting for application startup.
2023-04-24 14:40:14 | ERROR | stderr | INFO:     Application startup complete.
2023-04-24 14:40:14 | INFO | uvicorn.error | Application startup complete.
2023-04-24 14:40:14 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:40000 (Press CTRL+C to quit)
2023-04-24 14:40:14 | INFO | uvicorn.error | Uvicorn running on http://0.0.0.0:40000 (Press CTRL+C to quit)
2023-04-24 14:40:29 | INFO | model_worker | Send heart beat. Models: ['output_LLaVA-13B-v0']. Semaphore: None. global_counter: 0
2023-04-24 14:40:44 | INFO | model_worker | Send heart beat. Models: ['output_LLaVA-13B-v0']. Semaphore: None. global_counter: 0
2023-04-24 14:40:59 | INFO | model_worker | Send heart beat. Models: ['output_LLaVA-13B-v0']. Semaphore: None. global_counter: 0
2023-04-24 14:41:14 | INFO | model_worker | Send heart beat. Models: ['output_LLaVA-13B-v0']. Semaphore: None. global_counter: 0
2023-04-24 14:41:29 | INFO | model_worker | Send heart beat. Models: ['output_LLaVA-13B-v0']. Semaphore: None. global_counter: 0
2023-04-24 14:41:44 | INFO | model_worker | Send heart beat. Models: ['output_LLaVA-13B-v0']. Semaphore: None. global_counter: 0
2023-04-24 14:41:59 | INFO | model_worker | Send heart beat. Models: ['output_LLaVA-13B-v0']. Semaphore: None. global_counter: 0
2023-04-24 14:42:14 | INFO | model_worker | Send heart beat. Models: ['output_LLaVA-13B-v0']. Semaphore: None. global_counter: 0
2023-04-24 14:42:29 | INFO | model_worker | Send heart beat. Models: ['output_LLaVA-13B-v0']. Semaphore: None. global_counter: 0
2023-04-24 14:42:44 | INFO | model_worker | Send heart beat. Models: ['output_LLaVA-13B-v0']. Semaphore: None. global_counter: 0

4.
python -m llava.serve.test_message --model-name output_LLaVA-13B-v0 --controller http://localhost:10000
Models: ['output_LLaVA-13B-v0']
worker_addr: http://localhost:40000
A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions.
Human: What are the key differences between renewable and non-renewable energy sources?
Assistant: Renewable energy sources are those that can be replenished naturally in a relatively short amount of time, such as solar, wind, hydro, geothermal, and biomass. Non-renewable energy sources, on the other hand, are finite and will eventually be depleted, such as coal, oil, and natural gas. Here are some key differences between renewable and non-renewable energy sources:
1. Availability: Renewable energy sources are virtually inexhaustible, while non-renewable energy sources are finite and will eventually run out.
2. Environmental impact: Renewable energy sources have a much lower environmental impact than non-renewable sources, which can lead to air and water pollution, greenhouse gas emissions, and other negative effects.
3. Cost: Renewable energy sources can be more expensive to initially set up, but they typically have lower operational costs than non-renewable sources.
4. Reliability: Renewable energy sources are often more reliable and can be used in more remote locations than non-renewable sources.
5. Flexibility: Renewable energy sources are often more flexible and can be adapted to different situations and needs, while non-renewable sources are more rigid and inflexible.
6. Sustainability: Renewable energy sources are more sustainable over the long term, while non-renewable sources are not, and their depletion can lead to economic and social instability.

Human: Tell me a story with more than 1000 words.
 weator що pu DISachsubsection mil Deнародten bound File filenameoolsPOST >>>ategory;; workcontext Offramço resetXT Digsert Palww agreSBN
<img width="1257" alt="屏幕截图 2023-04-24 143912" src="https://user-images.githubusercontent.com/49706142/233918710-ecedba3d-4578-4e25-9a78-db7d8bf216f4.png">

**Comment by haotian-liu** [comment] 2023-04-24 07:35
Hi, these prompts all look correct to me. Unfortunately, I am unsure about what the issue is. I wonder if you directly load your llama model, is it working correctly?  Or vicuna?

And is it an env installed from scratch?  i.e., are the tokenizer versions the same as the default?

**Comment by imzhaoruijie** [comment] 2023-04-24 09:05
Thanks for your patience!
I load the model which is genereted by apply_delta.
I found I did not install tokenizer. Then I installed default tokenizer and version is 3.4.1, but  the output of the test message is still unexpected.

I skip the step of " pip install -e ." The cli reminds me "consider using a build backend  support pep 660 support".

I will try to install an env  from scratch and see the results.

Thanks again!

**Comment by haotian-liu** [comment] 2023-04-25 18:43
Hi @imzhaoruijie maybe you would also need this `pip install --upgrade pip  # enable PEP 660 support`

Please let me know if there are any updates after installing the environment from scratch, and if there are further updates.  Thanks!

**Comment by yuwfan** [comment] 2023-04-25 18:51
I also have the same issue. I can confirm that I apply delta to the original llama 13b checkpoints and use llava models. Could you help to share the md5sum of your LLaVA model? Thanks! @haotian-liu

**Comment by haotian-liu** [comment] 2023-04-25 18:56
Hi @yuwfan of course!  Below is the `md5sum` for the converted LLaVA model.  Please let me know if there are any disparities.  Besides, would you mind sharing if you are building the environment from scratch based on the latest instructions?  Let me know if any further concerns.

```
95e1b235bf9921a5f1e1f387d87aa46e  ./added_tokens.json
395bf409a41a30abdbf0f8f611eec042  ./pytorch_model.bin.index.json
dc67bae5a78e59bafe37782e40763e7f  ./special_tokens_map.json
a05ef2e4e89a6cc411f6f46b5621ad1a  ./tokenizer_config.json
f64a72a6ddd8f35635606b2863fd6931  ./generation_config.json
aa21a374a965a0f6118355f901f47b94  ./pytorch_model-00003-of-00003.bin
eeec4125e9c7560836b4873b6f8e3025  ./tokenizer.model
9585dc8282cf1ea48c2ae2e07471db0c  ./pytorch_model-00001-of-00003.bin
481795ef4fcd5994bc1d4aa200b90abe  ./config.json
96e55e68ada8315601ee226633074398  ./pytorch_model-00002-of-00003.bin
```

**Comment by yuwfan** [comment] 2023-04-25 19:21
Thank you for the response! Yes, I built the environment from scratch following the latest instructions. Here are my md5sum for all the files under LLaVA-13B-v0. Can you share your files except for model files? Thanks!

```bash
95e1b235bf9921a5f1e1f387d87aa46e  added_tokens.json
0e42b09768749913cf937dad7c29203c  config.json
ccdf396b2fd194d3fb39f29acceb2624  generation_config.json
9585dc8282cf1ea48c2ae2e07471db0c  pytorch_model-00001-of-00003.bin
96e55e68ada8315601ee226633074398  pytorch_model-00002-of-00003.bin
70c0eeec77635d9b51b8f42360fe57d5  pytorch_model-00003-of-00003.bin
f8397131c74cc98e4b7cb9e609cf9fbc  pytorch_model.bin.index.json
dc67bae5a78e59bafe37782e40763e7f  special_tokens_map.json
7f249d120639c5c13d6d8c331bee38c9  tokenizer_config.json
ba7ce161fad40ac607fa4f29c1b98498  tokenizer.json
eeec4125e9c7560836b4873b6f8e3025  tokenizer.model
```

**Comment by haotian-liu** [comment] 2023-04-25 21:02
Hi @yuwfan I tried to do a conversion from scratch, and verified that the model is working correctly.  Some hash changes, and there are more matches between that and yours:

```
95e1b235bf9921a5f1e1f387d87aa46e  added_tokens.json
c692514d88900bdf7d710c3353bbc4e2  config.json
f64a72a6ddd8f35635606b2863fd6931  generation_config.json
9585dc8282cf1ea48c2ae2e07471db0c  pytorch_model-00001-of-00003.bin
96e55e68ada8315601ee226633074398  pytorch_model-00002-of-00003.bin
aa21a374a965a0f6118355f901f47b94  pytorch_model-00003-of-00003.bin
395bf409a41a30abdbf0f8f611eec042  pytorch_model.bin.index.json
dc67bae5a78e59bafe37782e40763e7f  special_tokens_map.json
a05ef2e4e89a6cc411f6f46b5621ad1a  tokenizer_config.json
eeec4125e9c7560836b4873b6f8e3025  tokenizer.model
```

It seems that the main differences are in these files, and I do not see `tokenizer.json` in my folder. Unfortunately I am unable to share `pytorch_model-00003-of-00003.bin` due to the LLaMA license.

```
c692514d88900bdf7d710c3353bbc4e2  config.json
f64a72a6ddd8f35635606b2863fd6931  generation_config.json
aa21a374a965a0f6118355f901f47b94  pytorch_model-00003-of-00003.bin
395bf409a41a30abdbf0f8f611eec042  pytorch_model.bin.index.json
2dfcf86dfa7b4e91b87ffa05faf044ff  tokenizer_config.json
```

I guess we may compare `pytorch_model.bin.index.json` to see what are the differences, and other files as well of course.

[diff_cfgs.zip](https://github.com/haotian-liu/LLaVA/files/11326853/diff_cfgs.zip)

Please let me know if you find anything potentially be the cause, or you've figured it out.  Also let me know if there are anything else I could do to help.  Thanks.

**Comment by yuwfan** [comment] 2023-04-27 20:22
@haotian-liu Thank you for the details. I compared `pytorch_model.bin.index.json` and didn't find the projector parameters in the model. Then I added the projector weight to the model and fixed the issue. Thank you for the help!

```bash
"model.mm_projector.bias": "pytorch_model-00003-of-00003.bin",
"model.mm_projector.weight": "pytorch_model-00003-of-00003.bin",
"model.norm.weight": "pytorch_model-00003-of-00003.bin"
```

**Comment by haotian-liu** [comment] 2023-05-01 04:05
@yuwfan Glad to hear that the issue has been resolved! I am closing this issue now.  If you have further concerns, please feel free to re-open or open a new issue.  Thanks!

**Closed by haotian-liu** 2023-05-01 04:05 UTC
